spring:
  application:
    name: learn-spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
           model: qwen2.5-coder
      embedding:
        options:
          model: nomic-embed-text

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG


